name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare cargo-lambda
      run: pip3 install ziglang && cargo install cargo-lambda
    - name: Build
      run: cargo lambda build
    - name: Run tests
      run: cargo test --verbose
